services:
  todo_app_db:
    image: postgres
    restart: always
    container_name: todo_app_pg
    env_file:
      - .env
    volumes:
      - pgdata_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 2s
      retries: 5
#    networks:
#      - backend

  todo_app_redis:
    image: "redis:7.2.5"
    container_name: todo_app_redis_db
    restart: always

#    networks:
#      - backend

  app:
    container_name: todo-list-app
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    environment:
      REDIS_URL: 'redis://todo_app_redis:6379/0'
      DB_HOST: todo_app_db

      API_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
        todo_app_db:
          condition: service_healthy
        todo_app_redis:
          condition: service_started
    volumes:
      - type: bind
        read_only: true
        source: "${AUTH_PRIVATE_KEY_PATH}"
        target: "${AUTH_PRIVATE_KEY_PATH}"
#    networks:
#      - backend
#networks:
#  backend:
#    driver:

volumes:
  pgdata_volume: