services:
  todo_app_db:
    image: postgres
    restart: always
    container_name: todo_app_pg
    env_file:
      - .env
    environment:
      - "POSTGRES_PASSWORD=todoapp"
      - "POSTGRES_USER=todoapp"
      - "POSTGRES_DB=todoapp"
    volumes:
      - pgdata_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 2s
      retries: 5
    networks:
      - backend

  todo_app_redis:
    image: "redis:7.2.5"
    container_name: todo_app_redis_db
    restart: always

    networks:
      - backend

  app:
    container_name: todo-list-app
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    environment:
      REDIS_URL: 'redis://todo_app_redis:6379/0'
      DB_HOST: todo_app_db
      AUTH_PRIVATE_KEY_PATH: "/usr/ssl/key.pem"
      API_HOST: 0.0.0.0
      DB_USERNAME: todoapp
      DB_PASSWORD: todoapp
      DB_DATABASE: todoapp

    ports:
      - "${API_PORT:-80}:{$API_PORT:-8000}"
    depends_on:
        todo_app_db:
          condition: service_healthy
        todo_app_redis:
          condition: service_started
    volumes:
      - type: bind
        read_only: true
        source: "${AUTH_PRIVATE_KEY_PATH}"
        target: "/usr/ssl/key.pem"
    networks:
      - backend
networks:
  backend:
    driver: 'bridge'

volumes:
  pgdata_volume: