"""Add sharing table

Revision ID: 0cca2e02439d
Revises: 770a851339ba
Create Date: 2024-07-05 01:05:45.354705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cca2e02439d'
down_revision: Union[str, None] = '770a851339ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_sharing',
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('update_tasks', sa.Boolean(), nullable=False),
    sa.Column('manage_task', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['task_lists.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('list_id', 'user_id')
    )
    op.add_column('task_lists', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_lists', 'public')
    op.drop_table('list_sharing')
    # ### end Alembic commands ###
