"""remove delete_at and add cascade

Revision ID: 770a851339ba
Revises: f01f9a41720b
Create Date: 2024-07-05 00:43:52.029660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '770a851339ba'
down_revision: Union[str, None] = 'f01f9a41720b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_lists', 'deleted_at')
    op.drop_constraint('tasks_list_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'task_lists', ['list_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_list_id_fkey', 'tasks', 'task_lists', ['list_id'], ['id'])
    op.add_column('task_lists', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
